### ISSUE TITLE
Abbie - Peer Review

### ISSUE THREAD

**Issue by abbieolson** [bencoziv/Deduper#1]
I'm genuinely curious why you choose to screenshot your scripts and put them in word documents (didn't you say you did that with demulti, too?). Good use of functions. This will really help you avoid getting lost in a sea of "if" statements when it comes to the actual body of your code. Additionally, your splitting of "CIGAR string" components into smaller functions was a good idea. I consolidated them into one, and I'm starting to think a method like yours would alleviate the debugging process more than mine. I also like your placement of test cases. They read well with the rest of the algorithm. Overall, it's clear that you comprehended the assignment. Good job!

**Comment by bencoziv** [comment]
Thanks Abbie! It's not screenshot, but actually directly copied from my IDE and when pasted it keeps the format. I'm not sure why.
